# Generated by Django 5.2.4 on 2025-08-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='smsadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('img', models.ImageField(default='', upload_to='image')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
