# Generated by Django 5.2.4 on 2025-10-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagementapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='smscategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='smssubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smssubcategoryname', models.CharField(max_length=50)),
            ],
        ),
    ]
