# Generated by Django 5.2.4 on 2025-10-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagementapp', '0002_smscategory_smssubcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smssubcategory',
            old_name='smssubcategoryname',
            new_name='subcategoryname',
        ),
        migrations.AddField(
            model_name='smssubcategory',
            name='categoryname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
