# Generated by Django 5.2.4 on 2025-10-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagementapp', '0003_rename_smssubcategoryname_smssubcategory_subcategoryname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='smsproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('mrp', models.CharField(max_length=50)),
                ('hsn', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('warrenty', models.CharField(max_length=50)),
                ('expiry', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='image')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
