# Generated by Django 5.2.4 on 2025-11-01 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagementapp', '0006_smsaccounts_smsfinalpurchase_smstemppurchase_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock',
            new_name='quantity',
        ),
    ]
