# Generated by Django 5.2.4 on 2025-11-01 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagementapp', '0007_rename_stock_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smsfinalpurchase',
            name='customerid',
        ),
    ]
