# Generated by Django 5.2.4 on 2025-11-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagementapp', '0008_remove_smsfinalpurchase_customerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='smsfinalsale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.CharField(max_length=50)),
                ('productname', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='smstempsale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billno', models.EmailField(max_length=50)),
                ('productname', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
