# Generated by Django 5.2.4 on 2025-11-08 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanagementapp', '0009_smsfinalsale_smstempsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsaccounts',
            name='date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
